[default]
depends = [
    "git",
    "i3",
    "niri",
    "zsh",
    "alacritty",
    "picom",
    "wezterm",
    "logseq",
    "syncthing",
]

[wezterm.files]
"wezterm.lua" = { target = "~/.wezterm.lua", type = "symbolic" }

[oh-my-posh.files]
"oh-my-posh.yaml" = { target = "~/.oh-my-posh.yaml", type = "symbolic" }

[starship.files]
"starship.toml" = { target = "~/.config/starship.toml", type = "symbolic" }

[git.files]
gitconfig = "~/.gitconfig"

[i3.files]
"i3/blocks/config" = "~/.config/i3blocks/config"
i3 = "~/.i3"

[niri.files]
"niri/config.kdl" = "~/.config/niri/config.kdl"
"hypr/hypridle.conf" = "~/.config/hypr/hypridle.conf"
"systemd/user/gnome-polkit.service" = "~/.config/systemd/user/gnome-polkit.service"
"DankMaterialShell/settings.json" = "~/.config/DankMaterialShell/settings.json"

[syncthing.files]
"systemd/user/syncthingtray.service" = "~/.config/systemd/user/syncthingtray.service"

[zsh.files]
"zsh/zshrc" = { target = "~/.zshrc", type = "template" }

[alacritty.files]
"alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[picom.files]
"picom.conf" = "~/.config/picom.conf"

[logseq.files]
"logseq/Preferences" = { target = "~/.config/Logseq/Preferences", type = "symbolic" }
